FROM php:apache

# Installiere OpenSSH-Server und OpenSSL
RUN apt-get update && \
    apt-get install -y openssh-server openssl && \
    apt-get clean

# Konfiguriere SSH-Verzeichnis
RUN mkdir /var/run/sshd

# Erstelle Benutzer 'admin' mit Passwort
RUN useradd -m -s /bin/bash admin && \
    echo "admin:password" | chpasswd

# Aktiviere Passwort-Authentifizierung in SSH
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config && \
    sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config

# Setze eine einfache Index-Datei
RUN echo "Hello from SSH-Target on Port 80" > /var/www/html/index.html

# Erstelle selbstsigniertes SSL-Zertifikat
RUN mkdir -p /etc/ssl/certs /etc/ssl/private && \
    openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
    -keyout /etc/ssl/private/apache.key \
    -out /etc/ssl/certs/apache.crt \
    -subj "/C=US/ST=State/L=City/O=Org/CN=ssh-target"

# Apache SSL aktivieren und eigene Konfiguration einbinden
RUN a2enmod ssl && \
    a2ensite default-ssl && \
    rm /etc/apache2/sites-enabled/default-ssl.conf

COPY apache-ssl.conf /etc/apache2/sites-enabled/default-ssl.conf

# Starte SSH und Apache
CMD service ssh start && apache2ctl -D FOREGROUND
